#!/usr/bin/env bash
exec 2>&1
source /etc/envvars

# Register service with consul agent
read -r -d '' CONSUL_SERVICE_CONFIG <<- EOM
{
  "id": "${CONSUL_SERVICE_ADDRESS}",
  "name": "${CONSUL_SERVICE_NAME}",
  "address": "${CONSUL_SERVICE_ADDRESS}",
  "port": ${CONSUL_SERVICE_PORT},
  "check": {
    "id": "${CONSUL_SERVICE_ADDRESS}",
    "name": "General amiup check on elophant-web servers",
    "http": "${HEALTH_CHECK_ADDRESS}",
    "interval": "15s",
    "timeout": "10s"
  }
}
EOM
curl -X PUT -H "content-type:application/json" --data "${CONSUL_SERVICE_CONFIG}" ${CONSUL_CLIENT_ADDRESS}/v1/agent/service/register

rm -f /usr/local/lib/elophant-web/RUNNING_PID
exec /usr/local/lib/elophant-web/bin/elophant -Dconfig.file=/usr/local/lib/elophant-web/conf/application-${ELOPHANT_ENV}.conf
